

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx 
    image: nginx:alpine
    profiles:
      - blue
      - green
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/template.conf:/etc/nginx/template.conf
      - ./nginx/sig-app.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/ssl/certs
      - ./ssl-private:/etc/ssl/private
    env_file:
      - .env
      - local.env
    environment:
      - TARGET_SERVER=blue:8081
    networks:
      - app-network
    depends_on:
      - blue
      - green
    
  blue:
    container_name: blue
    profiles:
      - blue
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP_PORT=8081
        - APP_CMD=${APP_CMD}
        - APP_SOURCE_PATH=${APP_SOURCE_PATH}
    environment:
      - APP_PORT=8081
    networks:
      - app-network
    ports:
      - "8081:8081"
    labels:
      - "traefik.enable=false"
    command: clojure -M:production:server start -p 8081

  green:
    container_name: green
    profiles:
      - green
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP_PORT=8082        
    environment:
      - APP_PORT=8082
    networks:
      - app-network
    ports:
      - "8082:8082"
    labels:
      - "traefik.enable=false"
    command: clojure -M:production:server start -p 8082

networks:
  app-network:
    driver: bridge

