version: '0.1-alpha'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/${NGINX_CONFIG:-local.conf}:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/ssl/certs
    environment:
      - SERVER_NAME=${SERVER_NAME}
      - SSL_CERT_FILE=${SSL_CERT_FILE}
      - SSL_KEY_FILE=${SSL_KEY_FILE}
    env_file:
      - .env
      - local.env
    network:
      - app-network
    depends_on:
      - public
      - candidate
	
  public:
    container_name: blue
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP_PORT=8081
	- APP_CMD=${APP_CMD}
	- APP_SOURCE_PATH=${APP_SOURCE_PATH}
    environment:
      - APP_PORT=8081
      - APP_ENV=production
    network:
      - app-network
    profiles: ["public"]
    labels:
      - "traefik.enable=false"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8081/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

  candidate:
    container_name: green
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP_PORT=8082
	- APP_CMD=${APP_CMD}
	- APP_SOURCE_PATH=${APP_SOURCE_PATH}
    environment:
      - APP_PORT=8082
      - APP_ENV=production
    network:
      - app-network
    profiles: ["candidate"]
    labels:
      - "traefik.enable=false"    
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8082/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

  networks:
    app-network:
      driver: bridge

  app:
    image: nginx:alpine
    container_name: app
    profiles:
      - blue
      - green
    ports:
      - "${PORT-80}:80"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
      