

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx 
    image: nginx:alpine
    profiles:
      - blue
      - green
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sig-app.conf:/etc/nginx/templates/sig-app.conf.template
      - ./ssl:/etc/ssl/certs
      - ./ssl-private:/etc/ssl/private
    env_file:
      - .env
      - local.env
    environment:
      - TARGET_SERVER=blue:8081
    networks:
      - app_network
    depends_on:
      - blue
      - green
    command: /bin/sh -c "envsubst '$$TARGET_SERVER' < /etc/nginx/templates/sig-app.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    
  blue:
    container_name: blue
    profiles:
      - blue
    build:
      context: .
      dockerfile: Dockerfile
      args:
         APP_PORT: "8081"
         GIT_REPO: ${GIT_REPO}
         GIT_BRANCH: ${BLUE_BRANCH}
         APP_CMD: ${APP_CMD}
         APP_NAME: ${APP_NAME}
    environment:
      - APP_PORT=8081
    networks:
      - app_network
    ports:
      - "8081:8081"
    labels:
      - "traefik.enable=false"
    command: ${APP_CMD} -p 8081

  green:
    container_name: green
    profiles:
      - green
    build:
      context: .
      dockerfile: Dockerfile
      args:
         APP_PORT: "8082"
         GIT_REPO: ${GIT_REPO}
         GIT_BRANCH: ${GREEN_BRANCH}
         APP_CMD: ${APP_CMD}
         APP_NAME: ${APP_NAME}
    environment:
      - APP_PORT=8082
    networks:
      - app_network
    ports:
      - "8082:8082"
    labels:
      - "traefik.enable=false"
    command: ${APP_CMD} -p 8082

networks:
  app_network:
    driver: bridge

